"""American English — reglas de naturalización.

Contracciones estándar, reducciones informales (gonna, wanna, kinda)
y expresiones coloquiales seguras.  Sin reemplazo de palabras sueltas
que puedan romper el contexto.
"""

RULES = [
    # ── Contracciones negativas ──────────────────────────────────────
    (r"\bdo not\b",        "don't"),
    (r"\bdoes not\b",      "doesn't"),
    (r"\bdid not\b",       "didn't"),
    (r"\bis not\b",        "isn't"),
    (r"\bare not\b",       "aren't"),
    (r"\bwas not\b",       "wasn't"),
    (r"\bwere not\b",      "weren't"),
    (r"\bhave not\b",      "haven't"),
    (r"\bhas not\b",       "hasn't"),
    (r"\bhad not\b",       "hadn't"),
    (r"\bwill not\b",      "won't"),
    (r"\bwould not\b",     "wouldn't"),
    (r"\bshould not\b",    "shouldn't"),
    (r"\bcould not\b",     "couldn't"),
    (r"\bmight not\b",     "mightn't"),
    (r"\bmust not\b",      "mustn't"),
    (r"\bcannot\b",        "can't"),
    (r"\bcan not\b",       "can't"),
    # ── Contracciones sujeto + verbo ──────────────────────────────────
    (r"\bI am\b",          "I'm"),
    (r"\byou are\b",       "you're"),
    (r"\bhe is\b",         "he's"),
    (r"\bshe is\b",        "she's"),
    (r"\bit is\b",         "it's"),
    (r"\bwe are\b",        "we're"),
    (r"\bthey are\b",      "they're"),
    (r"\bI will\b",        "I'll"),
    (r"\byou will\b",      "you'll"),
    (r"\bhe will\b",       "he'll"),
    (r"\bshe will\b",      "she'll"),
    (r"\bwe will\b",       "we'll"),
    (r"\bthey will\b",     "they'll"),
    (r"\bI have\b",        "I've"),
    (r"\byou have\b",      "you've"),
    (r"\bwe have\b",       "we've"),
    (r"\bthey have\b",     "they've"),
    (r"\bI would\b",       "I'd"),
    (r"\byou would\b",     "you'd"),
    (r"\bhe would\b",      "he'd"),
    (r"\bshe would\b",     "she'd"),
    (r"\bwe would\b",      "we'd"),
    (r"\bthey would\b",    "they'd"),
    (r"\bI had\b",         "I'd"),
    # ── Reducciones informales (gonna, wanna, etc.) ──────────────────
    (r"\bgive me\b",       "gimme"),
    (r"\bgoing to\b",      "gonna"),
    (r"\bwant to\b",       "wanna"),
    (r"\bkind of\b",       "kinda"),
    (r"\bsort of\b",       "sorta"),
    (r"\blot of\b",        "lotta"),
    (r"\bI do not know\b", "idk",         True),
    (r"\bdo not know\b",   "dunno"),
    (r"\bbecause\b",       "cuz"),
    (r"\bthanks\b",        "thx"),
    (r"\bplease\b",        "pls"),
    # ── Expresiones coloquiales (frases completas) ───────────────────
    (r"\bwhat is up\b",    "what's up"),
    (r"\byou are welcome\b", "no problem"),
    (r"\bsee you later\b", "later"),
    (r"\bgoodbye\b",       "see ya"),
]
