"""Argentino — reglas de naturalización.

Voseo (vos, tenés, sos, podés), lunfardo y coloquialismos rioplatenses.

EXPERIMENTAL: algunas frases pueden contener errores.
"""

from ..engine import Rule, RulePriority

RULES = [
    # ── Voseo: frases completas (CRITICAL) ────────────────────────────
    Rule(r"\btú tienes que\b",    "vos tenés que",
         priority=RulePriority.CRITICAL,
         description="Voseo: 'tú tienes que' → 'vos tenés que'"),
    Rule(r"\bno me gusta\b",      "no me copa",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'no me gusta' → 'no me copa'"),
    Rule(r"\bme alegro\b",        "qué bueno che",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'me alegro' → 'qué bueno che'"),
    Rule(r"\bqué bueno\b",        "qué bueno che",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'qué bueno' → 'qué bueno che'"),
    Rule(r"\bcuídate\b",          "cuidate che",
         priority=RulePriority.CRITICAL,
         description="Despedida: 'cuídate' → 'cuidate che'"),
    Rule(r"\bestoy cansado\b",    "estoy re quemado",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'estoy cansado' → 'estoy re quemado'"),
    Rule(r"\bestá cansado\b",     "está re quemado",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'está cansado' → 'está re quemado'"),
    Rule(r"\bhace calor\b",       "calor del orto",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'hace calor' → 'calor del orto'"),
    Rule(r"\bhace frío\b",        "frío del orto",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'hace frío' → 'frío del orto'"),

    # ── Voseo: tú → vos (HIGH) ────────────────────────────────────────
    Rule(r"\btú tienes\b",        "vos tenés",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú tienes' → 'vos tenés'"),
    Rule(r"\btú eres\b",          "vos sos",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú eres' → 'vos sos'"),
    Rule(r"\btú puedes\b",        "vos podés",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú puedes' → 'vos podés'"),
    Rule(r"\btú quieres\b",       "vos querés",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú quieres' → 'vos querés'"),
    Rule(r"\btú sabes\b",         "vos sabés",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú sabes' → 'vos sabés'"),
    Rule(r"\btú dices\b",         "vos decís",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú dices' → 'vos decís'"),
    Rule(r"\btú haces\b",         "vos hacés",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú haces' → 'vos hacés'"),
    Rule(r"\btú vienes\b",        "vos venís",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú vienes' → 'vos venís'"),
    Rule(r"\btú piensas\b",       "vos pensás",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú piensas' → 'vos pensás'"),
    Rule(r"\btú entiendes\b",     "vos entendés",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú entiendes' → 'vos entendés'"),
    Rule(r"\btú necesitas\b",     "vos necesitás",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú necesitas' → 'vos necesitás'"),
    Rule(r"\btú estás\b",         "vos estás",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú estás' → 'vos estás'"),
    Rule(r"\btú andas\b",         "vos andás",
         priority=RulePriority.HIGH,
         description="Voseo: 'tú andas' → 'vos andás'"),

    # ── Saludos y cortesía (HIGH) ─────────────────────────────────────
    Rule(r"\bmuchas gracias\b",   "gracias che",
         priority=RulePriority.HIGH,
         description="Saludo: 'muchas gracias' → 'gracias che'"),
    Rule(r"¿cómo estás\??\b",   "¿cómo andás?",
         priority=RulePriority.HIGH,
         description="Saludo: 'cómo estás' → 'cómo andás'"),
    Rule(r"¿cómo está\??\b",    "¿cómo anda?",
         priority=RulePriority.HIGH,
         description="Saludo: 'cómo está' → 'cómo anda'"),
    Rule(r"\bmucho gusto\b",      "un placer che",
         priority=RulePriority.HIGH,
         description="Cortesía: 'mucho gusto' → 'un placer che'"),
    Rule(r"\bpor favor\b",        "porfa",
         priority=RulePriority.HIGH,
         description="Cortesía: 'por favor' → 'porfa'"),
    Rule(r"\bhasta luego\b",      "chau",
         priority=RulePriority.HIGH,
         description="Despedida: 'hasta luego' → 'chau'"),
    Rule(r"\badiós\b",            "chau",
         priority=RulePriority.HIGH,
         description="Despedida: 'adiós' → 'chau'"),

    # ── Afirmaciones / acuerdo (HIGH) ─────────────────────────────────
    Rule(r"\bestá bien\b",        "dale",
         priority=RulePriority.HIGH,
         description="Afirmación: 'está bien' → 'dale'"),
    Rule(r"\bde acuerdo\b",       "dale",
         priority=RulePriority.HIGH,
         description="Afirmación: 'de acuerdo' → 'dale'"),
    Rule(r"\bno importa\b",       "no pasa nada",
         priority=RulePriority.HIGH,
         description="Afirmación: 'no importa' → 'no pasa nada'"),
    Rule(r"\bpor supuesto\b",     "obvio",
         priority=RulePriority.HIGH,
         description="Afirmación: 'por supuesto' → 'obvio'"),
    Rule(r"\bexacto\b",           "obvio",
         priority=RulePriority.HIGH,
         description="Afirmación: 'exacto' → 'obvio'"),

    # ── Lunfardo / coloquialismos (MEDIUM) ────────────────────────────
    Rule(r"\bchico\b",            "pibe",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chico' → 'pibe'"),
    Rule(r"\bchica\b",            "piba",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chica' → 'piba'"),
    Rule(r"\bchicos\b",           "pibes",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chicos' → 'pibes'"),
    Rule(r"\bamigo\b",            "boludo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amigo' → 'boludo' (entre amigos)"),
    Rule(r"\bamiga\b",            "boluda",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amiga' → 'boluda'"),
    Rule(r"\bamigos\b",           "boludos",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amigos' → 'boludos'"),
    Rule(r"\bgenial\b",           "copado",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'genial' → 'copado'"),
    Rule(r"\bdivertido\b",        "copado",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'divertido' → 'copado'"),
    Rule(r"\bdivertida\b",        "copada",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'divertida' → 'copada'"),
    Rule(r"\bdinero\b",           "guita",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'dinero' → 'guita'"),
    Rule(r"\btrabajar\b",         "laburar",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'trabajar' → 'laburar'"),
    Rule(r"\btrabajo\b",          "laburo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'trabajo' → 'laburo'"),
    Rule(r"\btrabaja\b",          "labura",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'trabaja' → 'labura'"),
    Rule(r"\bestúpido\b",         "boludo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'estúpido' → 'boludo'"),
    Rule(r"\bestúpida\b",         "boluda",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'estúpida' → 'boluda'"),
    Rule(r"\bautobús\b",          "bondi",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'autobús' → 'bondi'"),
    Rule(r"\bcolectivo\b",        "bondi",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'colectivo' → 'bondi'"),
    Rule(r"\bdesorden\b",         "quilombo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'desorden' → 'quilombo'"),
    Rule(r"\blío\b",              "quilombo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'lío' → 'quilombo'"),
    Rule(r"\bproblema\b",         "quilombo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'problema' → 'quilombo'"),
    Rule(r"\bmujer\b",            "mina",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'mujer' → 'mina' (informal)"),
    Rule(r"\bbueno\b",            "bue",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'bueno' → 'bue' (informal)"),
]
