"""Colombiano — reglas de naturalización.

Coloquialismos y expresiones típicas de Colombia.

EXPERIMENTAL: algunas frases pueden contener errores.
"""

from ..engine import Rule, RulePriority

RULES = [
    # ── Frases completas (CRITICAL) ────────────────────────────────────
    Rule(r"\bno me gusta\b",      "no me cuadra",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'no me gusta' → 'no me cuadra'"),
    Rule(r"\bme alegro\b",        "qué chévere",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'me alegro' → 'qué chévere'"),
    Rule(r"\bten cuidado\b",      "pilas",
         priority=RulePriority.CRITICAL,
         description="Advertencia: 'ten cuidado' → 'pilas'"),
    Rule(r"\btenga cuidado\b",    "pilas",
         priority=RulePriority.CRITICAL,
         description="Advertencia: 'tenga cuidado' → 'pilas'"),
    Rule(r"\bcuídate\b",          "cuídate parce",
         priority=RulePriority.CRITICAL,
         description="Despedida: 'cuídate' → 'cuídate parce'"),

    # ── Saludos y cortesía (HIGH) ─────────────────────────────────────
    Rule(r"\bmuchas gracias\b",   "gracias parce",
         priority=RulePriority.HIGH,
         description="Saludo: 'muchas gracias' → 'gracias parce'"),
    Rule(r"¿cómo estás\??\b",   "¿qué más?",
         priority=RulePriority.HIGH,
         description="Saludo: 'cómo estás' → 'qué más'"),
    Rule(r"¿cómo está\??\b",    "¿qué más?",
         priority=RulePriority.HIGH,
         description="Saludo: 'cómo está' → 'qué más'"),
    Rule(r"\bmucho gusto\b",      "un placer parce",
         priority=RulePriority.HIGH,
         description="Cortesía: 'mucho gusto' → 'un placer parce'"),
    Rule(r"\bpor favor\b",        "porfa",
         priority=RulePriority.HIGH,
         description="Cortesía: 'por favor' → 'porfa'"),

    # ── Afirmaciones / acuerdo (HIGH) ─────────────────────────────────
    Rule(r"\bestá bien\b",        "listo",
         priority=RulePriority.HIGH,
         description="Afirmación: 'está bien' → 'listo'"),
    Rule(r"\bde acuerdo\b",       "listo",
         priority=RulePriority.HIGH,
         description="Afirmación: 'de acuerdo' → 'listo'"),
    Rule(r"\bno importa\b",       "no pasa nada",
         priority=RulePriority.HIGH,
         description="Afirmación: 'no importa' → 'no pasa nada'"),
    Rule(r"\bpor supuesto\b",     "claro que sí",
         priority=RulePriority.HIGH,
         description="Afirmación: 'por supuesto' → 'claro que sí'"),
    Rule(r"\bexacto\b",           "exacto parce",
         priority=RulePriority.HIGH,
         description="Afirmación: 'exacto' → 'exacto parce'"),

    # ── Coloquialismos léxicos (MEDIUM) ────────────────────────────────
    Rule(r"\bamigo\b",            "parcero",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amigo' → 'parcero'"),
    Rule(r"\bamiga\b",            "parcera",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amiga' → 'parcera'"),
    Rule(r"\bamigos\b",           "parceros",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amigos' → 'parceros'"),
    Rule(r"\bchico\b",            "parce",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chico' → 'parce'"),
    Rule(r"\bchicos\b",           "parceros",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chicos' → 'parceros'"),
    Rule(r"\bgenial\b",           "bacano",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'genial' → 'bacano'"),
    Rule(r"\bdivertido\b",        "bacano",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'divertido' → 'bacano'"),
    Rule(r"\bdivertida\b",        "bacana",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'divertida' → 'bacana'"),
    Rule(r"\bdinero\b",           "plata",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'dinero' → 'plata'"),
    Rule(r"\bniño\b",             "chino",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'niño' → 'chino'"),
    Rule(r"\bniña\b",             "china",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'niña' → 'china'"),
    Rule(r"\bniños\b",            "chinos",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'niños' → 'chinos'"),
    Rule(r"\btonto\b",            "huevón",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'tonto' → 'huevón'"),
    Rule(r"\btonta\b",            "huevona",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'tonta' → 'huevona'"),
]
