"""Venezolano — reglas de naturalización.

Coloquialismos y expresiones típicas de Venezuela.

EXPERIMENTAL: algunas frases pueden contener errores.
"""

from ..engine import Rule, RulePriority

RULES = [
    # ── Frases completas (CRITICAL: se aplican primero) ────────────────
    Rule(r"\bestoy de acuerdo\b",  "dale",
         priority=RulePriority.CRITICAL,
         description="Acuerdo completo: 'estoy de acuerdo' → 'dale'"),
    Rule(r"\bestá bromeando\b",    "está echando broma",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'está bromeando' → 'está echando broma'"),
    Rule(r"\bno me gusta\b",      "no me cuadra",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'no me gusta' → 'no me cuadra'"),
    Rule(r"\bestoy cansado\b",    "estoy molido",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'estoy cansado' → 'estoy molido'"),
    Rule(r"\bestá cansado\b",     "está molido",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'está cansado' → 'está molido'"),
    Rule(r"\bhace calor\b",       "está candela",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'hace calor' → 'está candela'"),
    Rule(r"\bhace frío\b",        "está fresco",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'hace frío' → 'está fresco'"),
    Rule(r"\bme alegro\b",        "qué bien",
         priority=RulePriority.CRITICAL,
         description="Expresión: 'me alegro' → 'qué bien'"),
    Rule(r"\bcuídate\b",          "cuídate mucho",
         priority=RulePriority.CRITICAL,
         description="Despedida: 'cuídate' → 'cuídate mucho'"),

    # ── Saludos y cortesía (HIGH) ─────────────────────────────────────
    Rule(r"\bmuchas gracias\b",   "gracias a ti",
         priority=RulePriority.HIGH,
         description="Saludo: 'muchas gracias' → 'gracias a ti'"),
    Rule(r"¿cómo estás\??\b",   "¿qué más?",
         priority=RulePriority.HIGH,
         description="Saludo: 'cómo estás' → 'qué más'"),
    Rule(r"¿cómo está\??\b",    "¿qué más?",
         priority=RulePriority.HIGH,
         description="Saludo: 'cómo está' → 'qué más'"),
    Rule(r"\bmucho gusto\b",      "un placer",
         priority=RulePriority.HIGH,
         description="Cortesía: 'mucho gusto' → 'un placer'"),
    Rule(r"\bpor favor\b",        "porfa",
         priority=RulePriority.HIGH,
         description="Cortesía: 'por favor' → 'porfa'"),

    # ── Afirmaciones / acuerdo (HIGH) ─────────────────────────────────
    Rule(r"\bde acuerdo\b",       "dale",
         priority=RulePriority.HIGH,
         description="Afirmación: 'de acuerdo' → 'dale'"),
    Rule(r"\bestá bien\b",        "vale",
         priority=RulePriority.HIGH,
         description="Afirmación: 'está bien' → 'vale'"),
    Rule(r"\bno importa\b",       "da igual",
         priority=RulePriority.HIGH,
         description="Afirmación: 'no importa' → 'da igual'"),
    Rule(r"\bpor supuesto\b",     "claro que sí",
         priority=RulePriority.HIGH,
         description="Afirmación: 'por supuesto' → 'claro que sí'"),

    # ── Coloquialismos léxicos (MEDIUM) ────────────────────────────────
    Rule(r"\bchico\b",            "pana",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chico' → 'pana'"),
    Rule(r"\bchicos\b",           "panas",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'chicos' → 'panas'"),
    Rule(r"\bamigo\b",            "pana",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amigo' → 'pana'"),
    Rule(r"\bamigos\b",           "panas",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'amigos' → 'panas'"),
    Rule(r"\bgenial\b",           "chévere",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'genial' → 'chévere'"),
    Rule(r"\bmuy bueno\b",        "chévere",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'muy bueno' → 'chévere'"),
    Rule(r"\bexcelente\b",        "chévere",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'excelente' → 'chévere'"),
    Rule(r"\bdivertido\b",        "chévere",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'divertido' → 'chévere'"),
    Rule(r"\bdivertida\b",        "chévere",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'divertida' → 'chévere'"),
    Rule(r"\bdinero\b",           "plata",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'dinero' → 'plata'"),
    Rule(r"\bcosa\b",             "vaina",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'cosa' → 'vaina'"),
    Rule(r"\bcosas\b",            "vainas",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'cosas' → 'vainas'"),
    Rule(r"\bniño\b",             "chamo",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'niño' → 'chamo'"),
    Rule(r"\bniña\b",             "chama",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'niña' → 'chama'"),
    Rule(r"\bniños\b",            "chamos",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'niños' → 'chamos'"),
    Rule(r"\bestúpido\b",         "güevón",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'estúpido' → 'güevón'"),
    Rule(r"\bbroma\b",            "echar broma",
         priority=RulePriority.MEDIUM,
         description="Léxico: 'broma' → 'echar broma'"),

    # ── Expresiones (LOW) ──────────────────────────────────────────────
    Rule(r"\bno me gusta\b",     "no me cuadra",
         priority=RulePriority.LOW,
         description="Expresión: no me gusta → no me cuadra"),
]
